import type { IAMPolicy, InfrastructureIR, Resource } from "../../ir/types";
import { logicalLambdaRoleId } from "../../registry/services";
import { cdkExpressionFromValue } from "./cdkValueToTs";

function indentBlock(body: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return body
    .split("\n")
    .map((line) => (line.length ? `${pad}${line}` : line))
    .join("\n");
}

function emitCfnResource(r: Resource): string {
  const props = cdkExpressionFromValue(r.properties, 2);
  const depends =
    r.dependsOn && r.dependsOn.length > 0
      ? `,\n      dependsOn: [${r.dependsOn.map((d) => JSON.stringify(d)).join(", ")}]`
      : "";
  return `new cdk.CfnResource(this, ${JSON.stringify(r.logicalId)}, {
      type: ${JSON.stringify(r.type)},
      properties: ${props}${depends},
    });`;
}

function emitIamPolicy(p: IAMPolicy, index: number): string {
  const roleLogicalId = logicalLambdaRoleId(p.attachment.lambdaNodeId);
  const constructId = `IamPolicy${index}`;
  const statements = cdkExpressionFromValue(p.statements, 2);
  return `new cdk.CfnResource(this, ${JSON.stringify(constructId)}, {
      type: "AWS::IAM::Policy",
      properties: {
        PolicyName: ${JSON.stringify(`designer-${p.id}`)},
        Roles: [cdk.Fn.ref(${JSON.stringify(roleLogicalId)})],
        PolicyDocument: {
          Version: "2012-10-17",
          Statement: ${statements},
        },
      },
    });`;
}

/**
 * Generates a CDK (TypeScript) stack source file from a merged IR.
 * Run `cdk synth` in a CDK app that instantiates this stack to produce
 * CloudFormation templates under `cdk.out/`.
 */
export function emitCdkStackSource(ir: InfrastructureIR, stackClassName: string): string {
  const resourceLines = ir.resources.map((r) => emitCfnResource(r));
  const iamLines = ir.iamPolicies.map((p, i) => emitIamPolicy(p, i));

  const body = [...resourceLines, ...iamLines]
    .map((line) => indentBlock(line, 4))
    .join("\n\n");

  return `// Generated by aws_designer — do not edit by hand.
// Dependencies: aws-cdk-lib, constructs, typescript
import * as cdk from "aws-cdk-lib";
import type { Construct } from "constructs";

export class ${stackClassName} extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

${body}
  }
}
`;
}
