import type { GraphDocument } from "../domain/types";
import { cdkExpressionFromValue } from "../emit/cdk/cdkValueToTs";
import {
  getRelationship,
  lambdaReadsS3ConfigSchema,
  lambdaWritesS3ConfigSchema,
  s3TriggersLambdaConfigSchema,
} from "../registry/relationships";
import {
  getService,
  lambdaNodeConfigSchema,
  logicalBucketId,
  logicalLambdaId,
  logicalLambdaRoleId,
  s3NodeConfigSchema,
} from "../registry/services";
import type { CompileIssue, GenerateCdkResult } from "./types";

type JsonObject = Record<string, unknown>;

type ResourceSpec = {
  logicalId: string;
  type: string;
  properties: JsonObject;
  dependsOn?: string[];
};

function mergeNotificationConfiguration(a: JsonObject, b: JsonObject): JsonObject {
  const aLambda = (a.LambdaConfigurations as unknown[] | undefined) ?? [];
  const bLambda = (b.LambdaConfigurations as unknown[] | undefined) ?? [];
  return {
    ...a,
    ...b,
    LambdaConfigurations: [...aLambda, ...bLambda],
  };
}

function mergeResourceProperties(a: JsonObject, b: JsonObject): JsonObject {
  const out: JsonObject = { ...a };
  for (const [key, value] of Object.entries(b)) {
    if (key === "NotificationConfiguration") {
      const existing = out.NotificationConfiguration;
      if (
        existing &&
        typeof existing === "object" &&
        !Array.isArray(existing) &&
        value &&
        typeof value === "object" &&
        !Array.isArray(value)
      ) {
        out.NotificationConfiguration = mergeNotificationConfiguration(
          existing as JsonObject,
          value as JsonObject,
        );
        continue;
      }
    }
    const prev = out[key];
    if (
      prev &&
      typeof prev === "object" &&
      !Array.isArray(prev) &&
      value &&
      typeof value === "object" &&
      !Array.isArray(value)
    ) {
      out[key] = mergeResourceProperties(prev as JsonObject, value as JsonObject);
    } else {
      out[key] = value;
    }
  }
  return out;
}

function objectArnForBucket(bucketLogicalId: string): unknown {
  return {
    "Fn::Join": ["", ["arn:aws:s3:::", { Ref: bucketLogicalId }, "/*"]],
  };
}

function bucketArnForList(bucketLogicalId: string): unknown {
  return { "Fn::Join": ["", ["arn:aws:s3:::", { Ref: bucketLogicalId }]] };
}

function nodeById(doc: GraphDocument, id: string) {
  return doc.nodes.find((n) => n.id === id);
}

function emitCfnResourceSpec(r: ResourceSpec): string {
  const props = cdkExpressionFromValue(r.properties, 2);
  const depends =
    r.dependsOn && r.dependsOn.length > 0
      ? `,\n      dependsOn: [${r.dependsOn.map((d) => JSON.stringify(d)).join(", ")}]`
      : "";
  return `new cdk.CfnResource(this, ${JSON.stringify(r.logicalId)}, {
      type: ${JSON.stringify(r.type)},
      properties: ${props}${depends},
    });`;
}

function wrapStackClass(stackClassName: string, body: string): string {
  const indented = body
    .split("\n")
    .map((line) => (line.length ? `    ${line}` : line))
    .join("\n");

  return `// Generated by aws_designer — do not edit by hand.
// Dependencies: aws-cdk-lib, constructs, typescript
import * as cdk from "aws-cdk-lib";
import type { Construct } from "constructs";

export class ${stackClassName} extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

${indented}
  }
}
`;
}

/**
 * Validates the graph and emits a CDK stack class as TypeScript source.
 * There is no intermediate IR: CloudFormation-shaped values are built here and
 * rendered with cdk.Fn.* helpers.
 */
export function generateCdkFromGraph(
  doc: GraphDocument,
  stackClassName = "GeneratedGraphStack",
): GenerateCdkResult {
  const issues: CompileIssue[] = [];
  const resourcesById = new Map<string, ResourceSpec>();

  for (const node of doc.nodes) {
    const svc = getService(node.serviceId, node.serviceVersion);
    if (!svc) {
      issues.push({
        code: "unknown_service_version",
        message: `Unknown service "${node.serviceId}" version "${node.serviceVersion}".`,
        nodeId: node.id,
      });
      continue;
    }
    try {
      if (node.serviceId === "s3") {
        const cfg = s3NodeConfigSchema.parse(node.config);
        const bucketId = logicalBucketId(node.id);
        const properties: JsonObject = {};
        if (cfg.bucketName) properties.BucketName = cfg.bucketName;
        if (cfg.enforceEncryption) {
          properties.BucketEncryption = {
            ServerSideEncryptionConfiguration: [
              {
                ServerSideEncryptionByDefault: { SSEAlgorithm: "AES256" },
              },
            ],
          };
        }
        resourcesById.set(bucketId, {
          logicalId: bucketId,
          type: "AWS::S3::Bucket",
          properties,
        });
      } else {
        const cfg = lambdaNodeConfigSchema.parse(node.config);
        const fnId = logicalLambdaId(node.id);
        const roleId = logicalLambdaRoleId(node.id);
        resourcesById.set(roleId, {
          logicalId: roleId,
          type: "AWS::IAM::Role",
          properties: {
            AssumeRolePolicyDocument: {
              Version: "2012-10-17",
              Statement: [
                {
                  Effect: "Allow",
                  Principal: { Service: "lambda.amazonaws.com" },
                  Action: "sts:AssumeRole",
                },
              ],
            },
            ManagedPolicyArns: [
              "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
            ],
          },
        });
        resourcesById.set(fnId, {
          logicalId: fnId,
          type: "AWS::Lambda::Function",
          properties: {
            FunctionName: cfg.functionName,
            Handler: cfg.handler,
            Runtime: cfg.runtime,
            Role: { "Fn::GetAtt": [roleId, "Arn"] },
            Code: {
              ZipFile:
                'exports.handler = async () => ({ statusCode: 200, body: "ok" });',
            },
          },
          dependsOn: [roleId],
        });
      }
    } catch (e) {
      issues.push({
        code: "invalid_node_config",
        message:
          e instanceof Error
            ? e.message
            : "Invalid configuration for service node.",
        nodeId: node.id,
      });
    }
  }

  const permissionResources: ResourceSpec[] = [];
  const iamStatementsByLambda = new Map<string, JsonObject[]>();
  const lambdaConfigsByBucketLogicalId = new Map<string, unknown[]>();

  for (const edge of doc.edges) {
    const sourceNode = nodeById(doc, edge.sourceNodeId);
    const targetNode = nodeById(doc, edge.targetNodeId);
    if (!sourceNode || !targetNode) {
      issues.push({
        code: "edge_missing_node",
        message: "Edge references a node that does not exist.",
        edgeId: edge.id,
      });
      continue;
    }
    const rel = getRelationship(edge.relationshipId, edge.relationshipVersion);
    if (!rel) {
      issues.push({
        code: "unknown_relationship_version",
        message: `Unknown relationship "${edge.relationshipId}" version "${edge.relationshipVersion}".`,
        edgeId: edge.id,
      });
      continue;
    }
    if (
      rel.source !== sourceNode.serviceId ||
      rel.target !== targetNode.serviceId
    ) {
      issues.push({
        code: "relationship_direction_mismatch",
        message: `Relationship "${rel.id}" expects ${rel.source} → ${rel.target}, but edge connects ${sourceNode.serviceId} → ${targetNode.serviceId}.`,
        edgeId: edge.id,
      });
      continue;
    }

    try {
      if (rel.id === "lambda_reads_s3") {
        const cfg = lambdaReadsS3ConfigSchema.parse(edge.config);
        const bucketId = logicalBucketId(targetNode.id);
        const prefix = cfg.objectKeyPrefix ?? "";
        const objectResource =
          prefix.length > 0
            ? {
                "Fn::Sub": [
                  `arn:aws:s3:::\${Bucket}/${prefix.replace(/\/$/, "")}/*`,
                  { Bucket: { Ref: bucketId } },
                ],
              }
            : objectArnForBucket(bucketId);
        const statements: JsonObject[] = [
          {
            Effect: "Allow",
            Action: "s3:GetObject",
            Resource: objectResource,
          },
        ];
        if (cfg.includeListBucket) {
          statements.push({
            Effect: "Allow",
            Action: "s3:ListBucket",
            Resource: bucketArnForList(bucketId),
            ...(prefix
              ? {
                  Condition: {
                    StringLike: {
                      "s3:prefix": [`${prefix.replace(/\/$/, "")}*`],
                    },
                  },
                }
              : {}),
          });
        }
        const list = iamStatementsByLambda.get(sourceNode.id) ?? [];
        list.push(...statements);
        iamStatementsByLambda.set(sourceNode.id, list);
      } else if (rel.id === "lambda_writes_s3") {
        const cfg = lambdaWritesS3ConfigSchema.parse(edge.config);
        const bucketId = logicalBucketId(targetNode.id);
        const prefix = cfg.objectKeyPrefix ?? "";
        const objectResource =
          prefix.length > 0
            ? {
                "Fn::Sub": [
                  `arn:aws:s3:::\${Bucket}/${prefix.replace(/\/$/, "")}/*`,
                  { Bucket: { Ref: bucketId } },
                ],
              }
            : objectArnForBucket(bucketId);
        const stmt: JsonObject = {
          Effect: "Allow",
          Action: ["s3:PutObject", "s3:PutObjectAcl"],
          Resource: objectResource,
        };
        const list = iamStatementsByLambda.get(sourceNode.id) ?? [];
        list.push(stmt);
        iamStatementsByLambda.set(sourceNode.id, list);
      } else if (rel.id === "s3_triggers_lambda") {
        const cfg = s3TriggersLambdaConfigSchema.parse(edge.config);
        const bucketId = logicalBucketId(sourceNode.id);
        const fnId = logicalLambdaId(targetNode.id);
        const permissionId = `lambda-permission-s3-${edge.id}`;
        const filterRules: { Name: string; Value: string }[] = [];
        if (cfg.prefix) filterRules.push({ Name: "prefix", Value: cfg.prefix });
        if (cfg.suffix) filterRules.push({ Name: "suffix", Value: cfg.suffix });
        const lambdaConfigurations = cfg.events.map((event) => {
          const entry: Record<string, unknown> = {
            Event: event,
            Function: { "Fn::GetAtt": [fnId, "Arn"] },
          };
          if (filterRules.length > 0) {
            entry.Filter = { S3Key: { Rules: filterRules } };
          }
          return entry;
        });
        const existing = lambdaConfigsByBucketLogicalId.get(bucketId) ?? [];
        lambdaConfigsByBucketLogicalId.set(bucketId, [
          ...existing,
          ...lambdaConfigurations,
        ]);
        permissionResources.push({
          logicalId: permissionId,
          type: "AWS::Lambda::Permission",
          properties: {
            Action: "lambda:InvokeFunction",
            FunctionName: { Ref: fnId },
            Principal: "s3.amazonaws.com",
            SourceArn: { "Fn::GetAtt": [bucketId, "Arn"] },
            SourceAccount: { Ref: "AWS::AccountId" },
          },
        });
      }
    } catch (e) {
      issues.push({
        code: "invalid_edge_config",
        message:
          e instanceof Error
            ? e.message
            : "Invalid configuration for relationship edge.",
        edgeId: edge.id,
      });
    }
  }

  for (const [bucketLid, configs] of lambdaConfigsByBucketLogicalId) {
    const res = resourcesById.get(bucketLid);
    if (!res) {
      issues.push({
        code: "notification_without_bucket",
        message: `S3 notification targets bucket logical id "${bucketLid}" but no bucket resource was created for that node.`,
      });
      continue;
    }
    res.properties = mergeResourceProperties(res.properties, {
      NotificationConfiguration: { LambdaConfigurations: configs },
    });
  }

  const iamPolicyResources: ResourceSpec[] = [];
  let policyIdx = 0;
  for (const [lambdaNodeId, statements] of iamStatementsByLambda) {
    if (statements.length === 0) continue;
    const roleLid = logicalLambdaRoleId(lambdaNodeId);
    const logicalId = `designer-iam-policy-${policyIdx}`;
    iamPolicyResources.push({
      logicalId,
      type: "AWS::IAM::Policy",
      properties: {
        PolicyName: `designer-iam-${policyIdx}`,
        Roles: [{ Ref: roleLid }],
        PolicyDocument: {
          Version: "2012-10-17",
          Statement: statements,
        },
      },
    });
    policyIdx++;
  }

  const ordered: ResourceSpec[] = [];
  for (const node of doc.nodes) {
    if (node.serviceId === "s3") {
      const spec = resourcesById.get(logicalBucketId(node.id));
      if (spec) ordered.push(spec);
    } else if (node.serviceId === "lambda") {
      const roleSpec = resourcesById.get(logicalLambdaRoleId(node.id));
      const fnSpec = resourcesById.get(logicalLambdaId(node.id));
      if (roleSpec) ordered.push(roleSpec);
      if (fnSpec) ordered.push(fnSpec);
    }
  }
  ordered.push(...permissionResources);
  ordered.push(...iamPolicyResources);

  const body = ordered.map((r) => emitCfnResourceSpec(r)).join("\n\n");
  const cdkSource = wrapStackClass(stackClassName, body);

  return {
    ok: issues.length === 0,
    cdkSource,
    issues,
  };
}
